apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: platform.db
  namespace: vote
spec:
  tier: platform
  order: 100
  selector: ''
  serviceAccountSelector: ''
  ingress:
    - action: Allow
      protocol: TCP
      source:
        selector: app == "worker" || app == "result"
      destination:
        ports:
          - '5432'
  types:
    - Ingress